services:
  - type: web
    name: umgrow
    env: docker
    plan: free
    branch: main
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan config:clear && php artisan route:clear && php artisan view:clear"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host-from-render
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: umgrow
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
